packages:
  - "."
allowBuilds:
  esbuild: true
overrides:
  conventional-changelog-conventionalcommits: 9.3.1
minimumReleaseAgeExclude:
  - "@clidoc/core@1.0.0"
  - "@clidoc/yargs@0.1.0"
  - "vitest-command-line@0.9.0"
